services:
  ################################################################################
  # infrastructure services
  ################################################################################
  mongodb:
    image: mongo:7.0.28
    container_name: cdp-infra-mongodb
    volumes:
      - ./scripts/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.hello().ok"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ################################################################################
  localstack:
    image: localstack/localstack:4.3.0
    container_name: cdp-infra-localstack
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns,dynamodb,firehose,secretsmanager
      - LS_LOG=WARN
    healthcheck:
      test: ["CMD", "stat", "/tmp/READY"]
      interval: 3s
      start_period: 5s
      retries: 20

  ################################################################################
  redis:
    image: redis:7.2.3-alpine3.18
    container_name: cdp-infra-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      start_period: 2s
      retries: 5

  ################################################################################
  selenium-chrome:
    # Maybe move to just CI? Also track bring in the version we use in portal
    image: selenium/standalone-chrome:119.0
    container_name: selenium-chrome
    ports:
      - 4444:4444

  ################################################################################
  cdp-portal-frontend:
    image: defradigital/cdp-portal-frontend:${CDP_PORTAL_FRONTEND:-latest}
    container_name: cdp-portal-frontend
    depends_on:
      cdp-portal-backend:
        condition: service_started
      cdp-self-service-ops:
        condition: service_started
      cdp-user-service-backend:
        condition: service_started
      redis:
        condition: service_healthy
      cdp-portal-stubs:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 10

  ################################################################################
  cdp-portal-backend:
    image: defradigital/cdp-portal-backend:${CDP_PORTAL_BACKEND:-latest}
    container_name: cdp-portal-backend
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      cdp-self-service-ops:
        condition: service_started
      cdp-user-service-backend:
        condition: service_healthy
      cdp-portal-stubs:
        condition: service_healthy

  ################################################################################
  cdp-user-service-backend:
    image: defradigital/cdp-user-service-backend:${CDP_USER_SERVICE_BACKEND:-latest}
    container_name: cdp-user-service-backend
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      cdp-portal-stubs:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3001/health"]
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 30

  ################################################################################
  cdp-self-service-ops:
    image: defradigital/cdp-self-service-ops:${CDP_SELF_SERVICE_OPS:-latest}
    container_name: cdp-self-service-ops
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      cdp-portal-stubs:
        condition: service_healthy
    environment:
      - PORT=3009
      - ENABLE_SECURE_CONTEXT=false
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3009/health"]
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 10

  ################################################################################
  cdp-portal-stubs:
    image: defradigital/cdp-portal-stubs:${CDP_PORTAL_STUBS:-latest}
    container_name: cdp-portal-stubs
    ports:
      - 3939:3939
    environment:
      - PORT=3939
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3939/health"]
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 10

  ################################################################################
  cdp-notify:
    image: defradigital/cdp-notify:${CDP_NOTIFY:-latest}
    container_name: cdp-notify
    environment:
      - PORT=3007
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3007/health"]
      interval: 5s
      timeout: 2s
      start_period: 20s
      retries: 10

  ################################################################################
