name: Journey Tests

inputs:
  self-service-ops:
    required: false
    type: string
  portal-backend:
    required: false
    type: string
  portal-frontend:
    required: false
    type: string
  user-service-backend:
    required: false
    type: string
  portal-stubs:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/cdp-portal-journey-tests
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash

    - name: Start docker compose
      run: |
          CDP_SELF_SERVICE_OPS=${{inputs.self-service-ops}} \
          CDP_PORTAL_FRONTEND=${{inputs.portal-frontend}} \
          CDP_PORTAL_BACKEND=${{inputs.portal-backend}} \
          CDP_USER_SERVICE_BACKEND=${{inputs.user-service-backend}} \
          CDP_PORTAL_STUBS=${{inputs.portal-stubs}} \
          docker compose up --wait-timeout 300 -d --quiet-pull
      shell: bash
    - name: Run the tests
      run: |
        npm run test:github
        npm run report
      shell: bash
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
